### ISSUE TITLE
Update for .s2i from .sti

### ISSUE THREAD

**Issue by jfmatth** [openshift/sti-python#106]
when using .sti/ folder, a deprecation warning is thrown during assembly.

if you put your files in .s2i then no warning.

Docs should be updated accordingly, 2.7, 3.3, and 3.4

I can make a PR if preferred

**Comment by rhcarvalho** [comment]
Hi @jfmatth! I found a couple of outdated references in the [latest official docs](https://docs.openshift.org/latest/welcome/index.html) and one occurrence in the project's README in this repo.

Did you spot any usage of the deprecated name anywhere else? Thanks!

**Comment by bparees** [comment]
@rhcarvalho you didn't fix the 3.3 and 3.4 readmes

**Comment by bparees** [comment]
(and yes i merged it w/o checking if the other files needed updating, so my bad :) )

**Comment by rhcarvalho** [comment]
@bparees following up in https://github.com/openshift/sti-python/pull/111, because I was working on something else just a while ago, I was exceptionally in the context of a single image (the 2.7 subdir)...

**Comment by rhcarvalho** [comment]
thanks for catching it after the fact ;)
