### ISSUE TITLE
Don't put contrib and user source in the same directory

### ISSUE THREAD

**Issue by rhcarvalho** [openshift/sti-python#18]
Because files could be overridden inadvertently.

(Same applies to other images)

**Comment by mfojtik** [comment]
@rhcarvalho do you mean .bashrc? If so, then I think I agree (if you have .bashrc in your source repository, then you loose the SCL enable and you will be broken. We should set the HOME directory to one level up and add the .bashrc there maybe.

@bparees ideas?

**Comment by soltysh** [comment]
:+1: it's a leftover from the time when we had the ONBUILD actions defined in base image.

**Comment by bparees** [comment]
applies to more than python.

**Comment by bparees** [comment]
is there a reason this would be a problem to fix post-3.0?  if not, i suggest we do that.

**Comment by mfojtik** [comment]
@bparees i think I'm OK with fixing this post-3.0, but I don't see this as too much devel work.

**Comment by rhcarvalho** [comment]
@mfojtik I mean all of `contrib/`'s content, see [this](https://github.com/openshift/sti-python/blob/dd6b4fc29b1b20dcd79b9e238e87688efb7af2ed/3.3/Dockerfile#L21-L23), which includes `src/.bashrc` and now also `src/passwd.template`.

@bparees yes, applies to all images. I wouldn't create one issue per image, and didn't create the issue in `sti-base`  because the is no copying there.

**Comment by soltysh** [comment]
[Trelloed](https://trello.com/c/8DuUfXTD/591-clean-sti-python-image), please close.

**Comment by rhcarvalho** [comment]
sti-* have already been changed before moving away from contrib/src to contrib/etc.
