### ISSUE TITLE
.local/bin in the PATH

### ISSUE THREAD

**Issue by rhcarvalho** [openshift/sti-python#22]
We're [prepending `.local/bin` to the PATH](https://github.com/openshift/sti-python/blob/1b62c43ab05da476ede5381edb251cecf1c08907/3.3/Dockerfile#L11) env var, what could have unexpected effects if the user has executables in his repo under `.local/bin`.

AFAIK we add `.local/bin` to PATH because of how we use `pip` with the `--user` flag that will put.

Quoting @mfojtik:
> we should do absolute but not using HOME var

This is somehow related to #18 (maybe can be fixed together), but specific to sti-python.

@bparees @soltysh FYI

**Comment by mfojtik** [comment]
@rhcarvalho this is related:
https://github.com/sclorg/rhscl2dockerfile/issues/29

@bparees are we going to change this path for 3.0? (i think we should as moving to another directory in post-3.0 images might be migration pain)

**Comment by soltysh** [comment]
@mfojtik builds we do are always clean builds, in that case I don't think we need to worry about migration problems. I'm voting to have it done post-3.0 together with #18 @rhcarvalho mentioned.

**Comment by mfojtik** [comment]
@soltysh @rhcarvalho trello this then and close this

**Comment by bparees** [comment]
would you feel better if we moved it to the end of the path instead of the beginning?

**Comment by soltysh** [comment]
[Trelloed](https://trello.com/c/8DuUfXTD/591-clean-sti-python-image), please close.

**Comment by GrahamDumpleton** [comment]
What was the reason for not wanting to use HOME variable in creating the absolute path?

This issue has come as problem again in concrete way on #57 and #58.
