### ISSUE TITLE
I think the repo should be renamed S2I-python

### ISSUE THREAD

**Issue by thesteve0** [openshift/sti-python#26]

**Comment by mfojtik** [comment]
@thesteve0 all repos should... I think we will rename this after post 3.0

**Comment by mfojtik** [comment]
@thesteve0 we discussed this with @bparees and we will not rename the repos (at least not now) as it will require a lot of refactoring to vagrant plugin and other tooling we use. We can move this into Trello and prioritize it, but I guess this will get very low priority.
