### ISSUE TITLE
oc new-app detection for Python

### ISSUE THREAD

**Issue by GrahamDumpleton** [openshift/sti-python#85]
I realise this possibly needs to be a bug report against 'oc' in 'openshift/origin' repo, but wanted to raise it here first in case there is something I am missing.

In:

* https://github.com/openshift/origin/blob/b7de777c90fd892cd746c905c17d92710eae3de8/pkg/generate/source/detector.go#L69

The code for detecting Python when using 'oc new-app' against a repository, and which thus then triggers S2I using the images from this repository is:

```
// DetectPython detects Python source
func DetectPython(dir string) (*Info, bool) {
	return detect("python", dir, "requirements.txt", "config.py")
}
```

The problem is why is it checking for ``config.py``?

I cannot think of any valid reason why it would look for ``config.py`` as I know of no convention in Python where a file by that name is anything significant.

I suspect it should be looking for ``setup.py``.

That would make more sense given that ``assemble`` only treats ``requirements.txt`` and ``setup.py`` as anything special for triggering Python package installation.

```
if [[ -f requirements.txt ]]; then
  echo "---> Installing dependencies ..."
  pip install --user -r requirements.txt
fi

if [[ -f setup.py ]]; then
  echo "---> Installing application ..."
  python setup.py develop --user
fi
```

Comments?

**Comment by bparees** [comment]
@rhcarvalho I have a sense you already fixed this in new-app, right?

**Comment by bparees** [comment]
(confirmed. was fixed here: https://github.com/openshift/origin/pull/6587/files)
